// Helpers for the TimTec product chatbot.
// Certificate of Analysis and Safety Data Sheet PDFs are generated by
// https://structure.timtec.org, not by this repository.
(function (root, factory) {
  const api = factory();
  if (typeof module !== "undefined" && module.exports) {
    module.exports = api;
  }
  root.TimTecCatalog = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  const DOSES = ["1mg", "2mg", "5mg", "10mg", "15mg", "20mg", "30mg", "50mg"];

  // Legacy catalog exports still use a Tampa column name. Read it, but never
  // show that city. The customer-facing office is Kissimmee, Suite 301.
  const STOCK_KEYS = [
    "In Stock Kissimmee, FL",
    "InStock_Kissimmee",
    "In Stock Orlando, FL",
    "InStock_Orlando",
    "In Stock Tampa, FL",
    "InStock_Tampa",
  ];

  const STOCK_LABEL = "In stock (Kissimmee, FL)";

  const CONTACT = [
    "TimTec, LLC",
    "1950 East Irlo Bronson Memorial Highway, Suite 301",
    "Kissimmee, Florida 34744",
    "United States",
    "Phone: 302-292-8500",
    "Fax: 302-292-8520",
    "Email: timtec@timtec.org",
    "Website: www.timtec.org",
  ];

  const INQUIRY_TO = "timtec@timtec.org";
  const INQUIRY_CC = "ledger@timtec.org";

  const COA_PDF = "https://structure.timtec.org/api/coa/pdf?id=";
  const SDS_PDF = "https://structure.timtec.org/api/msds/pdf?id=";
  const COA_TOOL = "https://structure.timtec.org/coa";
  const SDS_TOOL = "https://structure.timtec.org/msds";

  function formatPurity(raw) {
    if (raw == null) return "N/A";
    const text = String(raw).trim();
    if (!text || text.toLowerCase() === "none" || text.toLowerCase() === "null") {
      return "N/A";
    }
    if (text.includes("%")) return text;
    const value = Number(text);
    if (!Number.isFinite(value)) return text;
    if (value > 0 && value <= 1) {
      const percent = Math.round(value * 1000) / 10;
      return `${percent}%`;
    }
    if (value > 1 && value <= 100) return `${value}%`;
    return text;
  }

  function formatMw(raw) {
    if (raw == null || raw === "") return "N/A";
    const value = Number(raw);
    if (!Number.isFinite(value)) return String(raw);
    return value.toFixed(2);
  }

  function formatAmount(raw) {
    if (raw == null || raw === "") return "N/A";
    const value = Number(raw);
    if (!Number.isFinite(value)) return String(raw);
    const shown = Number.isInteger(value) ? String(value) : String(value);
    return `${shown} mg`;
  }

  function displayPrice(raw) {
    if (raw == null) return "Request";
    const text = String(raw).trim();
    if (!text || text.toLowerCase().includes("request") || Number.isNaN(Number.parseFloat(text))) {
      return "Request";
    }
    return text.startsWith("$") ? text : `$${text}`;
  }

  function readStock(raw) {
    for (const key of STOCK_KEYS) {
      const value = raw[key];
      if (value != null && String(value).trim() !== "") return String(value).trim();
    }
    return "Check availability";
  }

  function normalizeProduct(raw) {
    const id = raw.TimTec_ID == null ? "" : String(raw.TimTec_ID).trim();
    const smiles = raw.SMILES == null ? "" : String(raw.SMILES).trim();
    const iupac = raw.IUPAC == null ? "" : String(raw.IUPAC).trim();
    const formula = raw["Brutto-formula"] ?? raw.Formula ?? raw.formula ?? "";
    const amountRaw = raw["Amount/mg"] ?? raw.Amount;
    return {
      id,
      smiles,
      iupac,
      formula: formula == null || formula === "" ? "N/A" : String(formula),
      molecularWeight: formatMw(raw["Molecular weight"] ?? raw.MolecularWeight),
      purity: formatPurity(raw["Purity %"] ?? raw.Purity),
      amount: formatAmount(amountRaw),
      leadTime: raw["Lead Time"] ? String(raw["Lead Time"]) : "N/A",
      stockLabel: STOCK_LABEL,
      stock: readStock(raw),
      prices: DOSES.map((dose) => ({
        dose,
        price: displayPrice(raw[`Price_${dose}`]),
      })),
    };
  }

  function searchCatalog(products, query, limit) {
    const max = limit == null ? 12 : limit;
    const q = String(query || "").trim().toLowerCase();
    if (!q) return { results: [], total: 0, capped: false };
    const exact = [];
    const partial = [];
    for (const product of products) {
      const id = product.id.toLowerCase();
      const smiles = product.smiles.toLowerCase();
      if (id === q || (smiles && smiles === q)) {
        exact.push(product);
      } else if (product.iupac && product.iupac.toLowerCase().includes(q)) {
        partial.push(product);
      }
    }
    const matches = exact.length ? exact : partial;
    return {
      results: matches.slice(0, max),
      total: matches.length,
      capped: matches.length > max,
    };
  }

  function structureImageUrl(smiles) {
    if (!smiles || smiles.length > 1800) return "";
    return `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/smiles/${encodeURIComponent(smiles)}/PNG?image_size=300x300`;
  }

  function inquiryMailto(product) {
    const subject = `TimTec inquiry ${product.id}`;
    const body = [
      `TimTec ID: ${product.id}`,
      `IUPAC: ${product.iupac || "N/A"}`,
      `SMILES: ${product.smiles || "N/A"}`,
      "",
      "Amount of interest (mg):",
      "",
      "Please confirm availability, pricing, and lead time.",
    ].join("\n");
    return `mailto:${INQUIRY_TO}?cc=${encodeURIComponent(INQUIRY_CC)}&subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  }

  function catalogRequestUrl(search) {
    const params = new URLSearchParams(search || "");
    const requested = params.get("catalog");
    if (requested && /^[A-Za-z0-9_./-]+$/.test(requested) && !requested.includes("..")) {
      return requested;
    }
    return "TimTec_CATALOG_SOURCE.json";
  }

  return {
    DOSES,
    STOCK_LABEL,
    CONTACT,
    INQUIRY_TO,
    INQUIRY_CC,
    COA_PDF,
    SDS_PDF,
    COA_TOOL,
    SDS_TOOL,
    formatPurity,
    formatMw,
    formatAmount,
    displayPrice,
    normalizeProduct,
    searchCatalog,
    structureImageUrl,
    inquiryMailto,
    catalogRequestUrl,
  };
});
